/*==============================================================================
  011 - Triggers  (PostgreSQL)

  Port of db/sqlserver/011_triggers.sql.

  SQL Server allows one trigger to cover INSERT, UPDATE and DELETE; PostgreSQL
  needs a separate trigger per operation when transition tables are involved,
  because OLD TABLE only exists for UPDATE/DELETE and NEW TABLE only for
  INSERT/UPDATE. So four source triggers become seven here, plus one that has
  no SQL Server counterpart (see ROWVERSION below).

  Three changes from what AWS SCT generated:

    * SCT worked around the missing transition table by having the function
      CREATE TEMPORARY TABLE ... WITH NO DATA on every fire. The functions here
      branch on TG_OP and read only the transition table that exists, which is
      both cheaper and clearer.

    * SCT serialized the audit row images with json_agg(), which produces a
      JSON *array*. SQL Server's FOR JSON PATH, WITHOUT_ARRAY_WRAPPER produces
      an *object*, and audit.vw_RecentChanges depends on that: jsonb_each_text
      needs an object to expand into key/value pairs. jsonb_build_object is
      used instead.

    * client.tr_ClientDirectory_Insert - the INSTEAD OF INSERT trigger on
      client.vw_ClientDirectory - is missing from SCT's output entirely. There
      is no trigger on that view anywhere in the generated file. It is written
      out again below.

  Statement-level triggers with transition tables are kept (rather than
  simplified to FOR EACH ROW) because they match SQL Server's set-based trigger
  semantics: one fire per statement, seeing all affected rows at once.

  Error numbers travel as SQLSTATE, so a harness asserts on the same value
  against both engines: THROW 50007 -> ERRCODE '50007'.
==============================================================================*/

SET client_min_messages = warning;


/*------------------------------------------------------------------------------
  Serializes one client row to a JSON object, matching the column list the
  SQL Server trigger passes to FOR JSON PATH.

  jsonb_build_object rather than to_jsonb(row): to_jsonb would include every
  column, including the rowversion bytes and the audit timestamps, which the
  SQL Server version deliberately leaves out.
------------------------------------------------------------------------------*/
CREATE OR REPLACE FUNCTION client.fn_client_rowimage(rec client.client)
RETURNS JSONB
AS
$BODY$
    SELECT jsonb_build_object(
        'clientid',       rec.clientid,
        'clientcode',     rec.clientcode,
        'clienttype',     rec.clienttype,
        'displayname',    rec.displayname,
        'firstname',      rec.firstname,
        'lastname',       rec.lastname,
        'legalname',      rec.legalname,
        'sin',            rec.sin,
        'businessnumber', rec.businessnumber,
        'provincecode',   rec.provincecode,
        'maritalstatus',  rec.maritalstatus,
        'isactive',       rec.isactive,
        'onboardeddate',  rec.onboardeddate);
$BODY$
LANGUAGE sql IMMUTABLE;

DROP TRIGGER IF EXISTS tr_journalline_nopostededits_after_update ON acct.journalline;
DROP TRIGGER IF EXISTS tr_journalline_nopostededits_after_delete ON acct.journalline;
DROP TRIGGER IF EXISTS tr_client_audit_after_insert ON client.client;
DROP TRIGGER IF EXISTS tr_client_audit_after_update ON client.client;
DROP TRIGGER IF EXISTS tr_client_audit_after_delete ON client.client;
DROP TRIGGER IF EXISTS tr_client_biu ON client.client;
DROP TRIGGER IF EXISTS tr_t1return_statushistory ON tax.t1return;
DROP TRIGGER IF EXISTS tr_clientdirectory_insert ON client.vw_clientdirectory;


/*==============================================================================
  client.tr_Client_BIU  -  ROWVERSION emulation

  Has no counterpart in db/sqlserver/011_triggers.sql: SQL Server maintains
  client.Client.RowVersion itself because the column is declared ROWVERSION.
  PostgreSQL has no such type, so the value is taken from a sequence and the
  column is protected against being written by hand - which is what ROWVERSION
  guarantees.

  This one is genuinely SCT's design; the only change is that the sequence
  lives in this schema rather than in SCT's extension-pack schema.
==============================================================================*/
CREATE OR REPLACE FUNCTION client.fn_tr_client_biu()
RETURNS trigger
AS
$BODY$
BEGIN
    IF ((TG_OP = 'INSERT' AND NEW.rowversion IS NOT NULL)
     OR (TG_OP = 'UPDATE' AND NEW.rowversion <> OLD.rowversion)) THEN
        RAISE EXCEPTION 'The column "rowversion" cannot be modified because it is an autogenerated column';
    END IF;
    NEW.rowversion := nextval('client.seq_rowversion');
    RETURN NEW;
END;
$BODY$
LANGUAGE plpgsql;

CREATE TRIGGER tr_client_biu
BEFORE INSERT OR UPDATE
ON client.client
FOR EACH ROW
EXECUTE FUNCTION client.fn_tr_client_biu();


/*==============================================================================
  acct.tr_JournalLine_NoPostedEdits

  Once an entry is posted its lines are immutable; a correction has to be made
  by a reversing entry. INSERT is deliberately not covered, because
  acct.usp_PostJournalEntry creates the entry as posted and then inserts its
  lines - guarding inserts too would make posting impossible.

  Note the consequence for deletes: because cascading deletes fire this
  trigger, a client that carries posted entries cannot be deleted. That is the
  intended reading of "the books are immutable", not an oversight.
==============================================================================*/
CREATE OR REPLACE FUNCTION acct.fn_tr_journalline_nopostededits()
RETURNS trigger
AS
$BODY$
BEGIN
    -- Both triggers below supply OLD TABLE, so "deleted" always exists here.
    IF EXISTS (SELECT 1
                 FROM deleted             AS d
                 JOIN acct.journalentry   AS e ON e.journalentryid = d.journalentryid
                WHERE e.isposted = 1) THEN
        RAISE EXCEPTION
            'Lines of a posted journal entry cannot be changed or deleted; post a reversing entry instead.'
            USING ERRCODE = '50007';
    END IF;
    RETURN NULL;
END;
$BODY$
LANGUAGE plpgsql;

CREATE TRIGGER tr_journalline_nopostededits_after_update
AFTER UPDATE ON acct.journalline
REFERENCING OLD TABLE AS deleted
FOR EACH STATEMENT EXECUTE FUNCTION acct.fn_tr_journalline_nopostededits();

CREATE TRIGGER tr_journalline_nopostededits_after_delete
AFTER DELETE ON acct.journalline
REFERENCING OLD TABLE AS deleted
FOR EACH STATEMENT EXECUTE FUNCTION acct.fn_tr_journalline_nopostededits();


/*==============================================================================
  client.tr_Client_Audit

  Writes a before/after image of every affected row to audit.ChangeLog.

  One function serves all three operations, branching on TG_OP so it only ever
  reads the transition table that exists. audit.ChangeLog.OldValues/NewValues
  are jsonb, and each payload is a JSON object - the shape
  audit.vw_RecentChanges expands with jsonb_each_text.
==============================================================================*/
CREATE OR REPLACE FUNCTION client.fn_tr_client_audit()
RETURNS trigger
AS
$BODY$
BEGIN
    IF TG_OP = 'INSERT' THEN
        INSERT INTO audit.changelog
            (schemaname, tablename, primarykeyvalue, operation, oldvalues, newvalues)
        SELECT 'client', 'Client', i.clientid::VARCHAR(100), 'I',
               NULL,
               client.fn_client_rowimage(i)
          FROM inserted AS i;

    ELSIF TG_OP = 'DELETE' THEN
        INSERT INTO audit.changelog
            (schemaname, tablename, primarykeyvalue, operation, oldvalues, newvalues)
        SELECT 'client', 'Client', d.clientid::VARCHAR(100), 'D',
               client.fn_client_rowimage(d),
               NULL
          FROM deleted AS d;

    ELSE
        INSERT INTO audit.changelog
            (schemaname, tablename, primarykeyvalue, operation, oldvalues, newvalues)
        SELECT 'client', 'Client', i.clientid::VARCHAR(100), 'U',
               client.fn_client_rowimage(d),
               client.fn_client_rowimage(i)
          FROM inserted AS i
          JOIN deleted  AS d ON d.clientid = i.clientid;
    END IF;

    RETURN NULL;
END;
$BODY$
LANGUAGE plpgsql;

CREATE TRIGGER tr_client_audit_after_insert
AFTER INSERT ON client.client
REFERENCING NEW TABLE AS inserted
FOR EACH STATEMENT EXECUTE FUNCTION client.fn_tr_client_audit();

CREATE TRIGGER tr_client_audit_after_update
AFTER UPDATE ON client.client
REFERENCING OLD TABLE AS deleted NEW TABLE AS inserted
FOR EACH STATEMENT EXECUTE FUNCTION client.fn_tr_client_audit();

CREATE TRIGGER tr_client_audit_after_delete
AFTER DELETE ON client.client
REFERENCING OLD TABLE AS deleted
FOR EACH STATEMENT EXECUTE FUNCTION client.fn_tr_client_audit();


/*==============================================================================
  tax.tr_T1Return_StatusHistory

  Records filing-status transitions. The row comparison is what avoids logging
  a write that set FilingStatus to the value it already had - the same reason
  the SQL Server version cannot rely on UPDATE(FilingStatus) alone.
==============================================================================*/
CREATE OR REPLACE FUNCTION tax.fn_tr_t1return_statushistory()
RETURNS trigger
AS
$BODY$
BEGIN
    INSERT INTO audit.returnstatushistory (t1returnid, oldstatus, newstatus)
    SELECT i.t1returnid, d.filingstatus, i.filingstatus
      FROM inserted AS i
      JOIN deleted  AS d ON d.t1returnid = i.t1returnid
     WHERE LOWER(i.filingstatus) <> LOWER(d.filingstatus);
    RETURN NULL;
END;
$BODY$
LANGUAGE plpgsql;

CREATE TRIGGER tr_t1return_statushistory
AFTER UPDATE ON tax.t1return
REFERENCING OLD TABLE AS deleted NEW TABLE AS inserted
FOR EACH STATEMENT EXECUTE FUNCTION tax.fn_tr_t1return_statushistory();


/*==============================================================================
  client.tr_ClientDirectory_Insert   (INSTEAD OF INSERT on a view)

  MISSING FROM THE SCT OUTPUT ENTIRELY - there is no trigger on
  client.vw_ClientDirectory anywhere in the generated file, and nothing in the
  conversion report says one was dropped.

  client.vw_ClientDirectory spans three tables and so is not insertable on its
  own. This makes it behave as though it were, fanning a single row out into
  the client, its primary address and its primary email.

  PostgreSQL INSTEAD OF triggers are FOR EACH ROW, which is simpler than the
  SQL Server original: no MERGE ... OUTPUT trick is needed to correlate the
  generated key back to its source row, because RETURNING INTO gives it
  directly for the one row in hand.
==============================================================================*/
CREATE OR REPLACE FUNCTION client.fn_tr_clientdirectory_insert()
RETURNS trigger
AS
$BODY$
DECLARE
    var_clientid INTEGER;
BEGIN
    IF NEW.clientcode IS NULL OR NEW.clienttype IS NULL OR NEW.provincecode IS NULL THEN
        RAISE EXCEPTION
            'ClientCode, ClientType and ProvinceCode are required when inserting through client.vw_ClientDirectory.'
            USING ERRCODE = '50008';
    END IF;

    INSERT INTO client.client
        (clientcode, clienttype, firstname, lastname, dateofbirth, sin,
         legalname, incorporationdate, businessnumber, fiscalyearendmonth,
         provincecode, onboardeddate, isactive)
    VALUES
        (NEW.clientcode,
         NEW.clienttype,
         NEW.firstname,
         NEW.lastname,
         -- The view does not expose these, so rows inserted this way get the
         -- placeholders that satisfy ck_client_typeshape.
         CASE WHEN NEW.clienttype = 'I' THEN DATE '1900-01-01' END,
         NEW.sin,
         NEW.legalname,
         CASE WHEN NEW.clienttype = 'C' THEN DATE '1900-01-01' END,
         NEW.businessnumber,
         CASE WHEN NEW.clienttype = 'C' THEN 12 END,
         NEW.provincecode,
         COALESCE(NEW.onboardeddate, (timezone('UTC', now()))::date),
         COALESCE(NEW.isactive, 1))
    RETURNING clientid INTO var_clientid;

    IF NEW.line1 IS NOT NULL AND NEW.city IS NOT NULL AND NEW.postalcode IS NOT NULL THEN
        INSERT INTO client.clientaddress
            (clientid, addresstype, line1, line2, city, provincecode, postalcode, isprimary)
        VALUES
            (var_clientid, 'Mailing', NEW.line1, NEW.line2, NEW.city,
             NEW.provincecode, NEW.postalcode, 1);
    END IF;

    IF NEW.primaryemail IS NOT NULL THEN
        INSERT INTO client.clientcontact (clientid, contacttype, contactvalue, isprimary)
        VALUES (var_clientid, 'Email', NEW.primaryemail, 1);
    END IF;

    RETURN NEW;
END;
$BODY$
LANGUAGE plpgsql;

CREATE TRIGGER tr_clientdirectory_insert
INSTEAD OF INSERT ON client.vw_clientdirectory
FOR EACH ROW EXECUTE FUNCTION client.fn_tr_clientdirectory_insert();
